### ISSUE TITLE
Alias fields return null from the application schema

### ISSUE THREAD

**Issue by email2vimalraj** [prismagraphql/prisma#2429] opened 2018-05-15 06:29 UTC
# Bug Report

**Current behavior**
When we use some alias for the fields while querying, we are getting null despite having data for those fields.

**Reproduction**
I've create a github repo which can be used to reproduce the issue:
https://github.com/email2vimalraj/prisma-alias-field

**Expected behavior?**
```
{
  "data": {
    "usersGroupedPosts": [
      {
        "name": "Vimal",
        "notPublished": [],
        "publishedPosts": [
          {
            "title": "Some title"
          }
        ]
      },
      {
        "name": "Bhuvana",
        "notPublished": [
          {
            "title": "Pending title"
          }
        ],
        "publishedPosts": [
          {
            "title": "New title"
          }
        ]
      }
    ]
  }
}
```

**Actual behavior**
```
{
  "data": {
    "usersGroupedPosts": [
      {
        "name": "Vimal",
        "notPublished": null,
        "publishedPosts": null
      },
      {
        "name": "Bhuvana",
        "notPublished": null,
        "publishedPosts": null
      }
    ]
  }
}
```

**Comment by email2vimalraj** [comment] 2018-05-17 09:38
@marktani : Any help here?

**Comment by email2vimalraj** [comment] 2018-05-25 05:11
@marktani : I'm trying to build the codebase and see if I can fix by myself and contribute back. But unfortunately, I'm failed. The contribution documentation need to be updated on steps to build the code base atleast that would help the beginners like me.

**Comment by divyenduz** [comment] 2018-05-26 10:58
Hi, @email2vimalraj Thanks for sharing this bug report and the reproduction repository (always helps and speeds up the process).

Essentially, you are running into [this issue](https://github.com/prismagraphql/prisma/issues/1896) and a solution for it is [already live](https://github.com/prismagraphql/graphql-yoga/pull/216) with latest version of graphql-yoga. 

But the reason that solution is not working for you is [this issue](https://github.com/apollographql/apollo-server/issues/865) i.e. custom resolver does not work with `tracing` and `cacheControl` yet. 

So, a temporary workaround is to start your server as follows:

```
const options = {
 tracing: false,
 cacheControl: false
};

server.start(options, () =>
 console.log("Server is running on http://localhost:4000")
);
```

I am closing this issue as other issues are already open to tackle the underlying problem. Please feel free to reopen in case you need further help. 

Thanks!

**Closed by divyenduz** 2018-05-26 10:58 UTC
Labels: triage/pending
