### ISSUE TITLE
"prisma list" command should display local deployed services

### ISSUE THREAD

**Issue by kevinmarrec** [prismagraphql/prisma#2904] opened 2018-08-09 23:42 UTC
**Describe the bug**
`prisma list` should displays local deployed services

**To Reproduce**
1. Setup a working server
2. `prisma deploy` -> Everything is ok and deployed
3. `prisma list` -> Displays `No deployed service found`

**Expected behavior**
`prisma list` should displays my local deployed service

**Screenshots**
![screenshot_3](https://user-images.githubusercontent.com/25272043/43931393-7c79895c-9c3e-11e8-800a-baf7fe6f699f.png)

**Versions:**
 - OS: `Windows 10`
 - `prisma` CLI: prisma/1.13.7 (linux-x64) node-v10.8.0

**Comment by marktani** [comment] 2018-08-10 07:40
Thanks for bringing this up, @kevinmarrec! I close this as a duplicate of #2764.

**Closed by marktani** 2018-08-10 07:40 UTC
