### ISSUE TITLE
Type xxxPreviousValues must define one or more fields.

### ISSUE THREAD

**Issue by ptpaterson** [prismagraphql/prisma#2710] opened 2018-06-29 20:27 UTC
**Describe the bug**
When a database type is defined with only relation fields, an associated `PreviousValues` helper type is created with no fields.  This causes an error during the `graphql get-schema --project database` command.

**To Reproduce**
The following schema generates the error `Type MyRelationTypePreviousValues must define one or more fields`

``` graphql
type MyDataType {
  """ fields... """

  oneRelations: [MyRelationType !]! @relation(name: "RelationOne")
  twoRelations: [MyRelationType !]! @relation(name: "RelationTwo")
}

type MyRelationType {
  one: Item! @relation(name: "RelationOne")
  two: Item! @relation(name: "RelationTwo")
}
```

**Expected behavior**
Either the PreviousValues type should not be created, or a warning/error should be created on deploy.  Since the deploy otherwise worked out okay, I was very confused and lost for a while trying to figure this one out.

**Versions (please complete the following information):**
 - `Windows 10`
 - prisma/1.10.2 (windows-x64) node-v8.9.4
 - Prisma Server: 1.11-beta (Heroku)
 - graphql-cli 2.16.3

**Comment by bardak-dev** [comment] 2018-07-01 16:34
+1

**Comment by marktani** [comment] 2018-07-03 16:45
Thanks a lot for this report, this looks related to #1981.

Can you share when exactly you ran into this specific error message?
This is a duplicate of https://github.com/prismagraphql/prisma/issues/2623, but there the error message is "Syntax Error: Expected Name, found }".

**Comment by ptpaterson** [comment] 2018-07-05 01:16
Thanks for response!

I was getting the error 5 days ago when the issue was posted.  I had just installed latest CLI tools.

**Comment by bardak-dev** [comment] 2018-07-11 10:55
I still have the problem.

GraphQL endpoint generated invalid schema: Type MyTypePreviousValues must define one or more fields.
Running graphql get-schema -p prisma ✖
$ prisma -v
prisma/1.11.1 (darwin-x64) node-v10.4.1
$ graphql -v
2.16.4

**Comment by bardak-dev** [comment] 2018-07-11 10:59
@marktani 
short version
`# Currency codes
enum CurrencyCode {
  # United States Dollars (USD)
  USD

  # Euro (EUR)
  EUR
}

type Money {
  # Decimal money amount.
  amount: Float!

  # Currency of the money.
  currencyCode: CurrencyCode!
}

type PaymentsPayoutSummary {
  #blankField: String @deprecated(reason: "get-schema bug")
  # Total fees for all adjustments including disputes.
  adjustmentsFee: Money! @relation(name: "PayoutSummaryAF")

  # Total gross amount for all adjustments including disputes.
  adjustmentsGross: Money! @relation(name: "PaymentsPayoutSummaryAG")
}`

**Comment by TheWillMundy** [comment] 2018-07-24 15:01
I had this same issue and adding a unique field of type ID or String solved the problem for me. In the future a better solution might come out, but for now this fix seems to work.

**Comment by marktani** [comment] 2018-08-09 14:50
Closing this as duplicate of https://github.com/prismagraphql/prisma/issues/2623.

**Closed by marktani** 2018-08-09 14:50 UTC
Labels: kind/bug, reproduction-available
