### ISSUE TITLE
Can't introspect database with specified schema name

### ISSUE THREAD

**Issue by Belobobr** [prismagraphql/prisma#2776] opened 2018-07-15 19:12 UTC
**Describe the bug**
Can't introspect database with specified schema

**To Reproduce**
1. Type prisma introspect
2. Type schema name when prompted:  "Enter name of existing schema"
3. Error: The provided database doesn't contain any tables. Please provide another database.

**Expected behavior**
Prisma have generated introspected schema

**Screenshots**
<img width="1680" alt="source" src="https://user-images.githubusercontent.com/5969678/42737387-156a1352-887b-11e8-9b5a-d5df93c9baf2.png">

**Versions (please complete the following information):**
 - prisma/1.11.1 (darwin-x64) node-v10.4.1

**Additional context**
Seems that prisma cli choose first available schema instead of schema being entered by user. Currently i use prisma cli sources for database introspection, because prisma-db-introspection package works fine.

**Comment by marktani** [comment] 2018-07-16 07:01
Duplicate of #2407, which is fixed on `alpha`.

**Closed by marktani** 2018-07-16 07:01 UTC
