### ISSUE TITLE
RethinkDB Connector

### ISSUE THREAD

**Issue by Th3Mouk** [prismagraphql/prisma#2475] opened 2018-05-19 21:11 UTC
# Feature Request

**What feature are you missing?**

RethinkDB Connector

**How could this feature look like in detail? Tradeoffs?**

Retrieving datas and implements basic filters like comparator and dates

**Comment by veksen** [comment] 2018-05-24 08:36
@marktani dupe of #2216

**Comment by marktani** [comment] 2018-05-24 09:35
Thanks @veksen :slightly_smiling_face:

**Closed by marktani** 2018-05-24 09:35 UTC
