### ISSUE TITLE
type with name "News" cannot be deployed

### ISSUE THREAD

**Issue by attilah** [prismagraphql/prisma#1772] opened 2018-01-30 06:15 UTC
**Current behavior**

I wanted to create a type named News but an error was returned

**Reproduction**

try to deploy this datamodel

```
type News {
  id: ID! @unique
}
```

Error:
```
ERROR: All fields within 'Query' type should have unique names! Non-unique fields: 'news'.

{
  "errors": [
    {
      "requestId": "api:api:cjd18y9me003d0138ifqm95q9",
      "message": "All fields within 'Query' type should have unique names! Non-unique fields: 'news'."
    }
  ],
  "status": 500
}
```

**Expected behavior?**

News type created.

**Comment by johannpinson** [comment] 2018-03-13 15:15
Same thing, but the model seems to be created well.
Just the generation of the schema looks fail (I check my RDS and the table "News" is created well)

![capture d ecran 2018-03-13 a 16 13 50](https://user-images.githubusercontent.com/2202989/37350662-a6cc98aa-26d9-11e8-8ebc-02fb915fdd0d.png)

**Comment by johannpinson** [comment] 2018-03-13 17:11
Related to #48

**Comment by marktani** [comment] 2018-03-13 17:46
Yup, the issue here is that the plural form of `News` will be `News` - so both queries for many news - `news: [News!]!` - and single news - `news: News` are called `news`, leading to the name clash.

**Comment by attilah** [comment] 2018-03-13 18:39
using ```all``` prefix for the collection, or an ```Item``` (NewsItem) suffix for the single ones is a good way, whatever fix you decide I think this option should be handed to the developer and make it a configurable option.

As a personal preference I like the ```News``` and ```NewsItem``` more.

**Comment by marktani** [comment] 2018-06-20 09:19
Closing as duplicate of #2659.

**Closed by marktani** 2018-06-20 09:19 UTC
Labels: kind/feature
