### ISSUE TITLE
Nested mutation inside upsert mutations are not applied 

### ISSUE THREAD

**Issue by KTITS-Kevin** [prismagraphql/prisma#1579] opened 2018-01-11 11:15 UTC
**Current behavior**
if i execute an upsert with a connect inside (running 1.0 beta4) i get the following error: "Unsupported scalar value in SlickExtensions: Some(ListMap(connect -> Some(ListMap(id -> Some(cjc99y7q4006e0181fulirnrj)))))"
If i run the upsert without the connect everything works fine.

**Reproduction**
```
type Customer{
id: ID! @unique
name: String!
tenant: Tenant! @relation:"TenantCustomers"
}

type Tenant{
id: ID! @unique
name: String!
customers: [Customer!]! @relation:"TenantCustomers"
}

mutation UpsertCustomer($id: ID!, $name: String!) {
upsertCustomer(where: {id: $id}, create: {name: $name, mandant:{connect:{id:"Your Tenant Value"}}}, update: {name: $name}) {
    id
    name
    mandant{id}
  }
}
```

**Result Playground**
```
{
  "data": null,
  "errors": [
    {
      "message": "Unsupported scalar value in SlickExtensions: ListMap(connect -> Some(ListMap(id -> Some(Your Value))))",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "upsertCustomer"
      ]
```
 
**Result Server Debug Log**
```
[GraphQL error]: Message: Unsupported scalar value in SlickExtensions: ListMap(connect -> Some(ListMap(id -> Some(Your Value)))), Location: [object Object], Path: upsertCustomer
Response from http://localhost:60001/XXX/dev:
null
Error: Unsupported scalar value in SlickExtensions: ListMap(connect -> Some(ListMap(id -> Some(Your Value))))
    at Object.checkResultAndHandleErrors (C:\dev\xxx\server\node_modules\graphql-tools\src\stitching\errors.ts:84:7)
    at Object.<anonymous> (C:\dev\xxx\server\node_modules\graphql-tools\src\stitching\delegateToSchema.ts:97:14)
    at step (C:\dev\xxx\server\node_modules\graphql-tools\dist\stitching\delegateToSchema.js:40:23)
    at Object.next (C:\dev\xxx\server\node_modules\graphql-tools\dist\stitching\delegateToSchema.js:21:53)
    at fulfilled (C:\dev\xxx\server\node_modules\graphql-tools\dist\stitching\delegateToSchema.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)


```

**Comment by Huvik** [comment] 2018-01-15 12:10
Can confirm that problem is still there with version `graphcool/1.0.0-beta4.1.1`

**Comment by Fi1osof** [comment] 2018-01-21 01:55
Got same error.
 [Bugsnag - local / testing] Error report: com.bugsnag.Report@226cd50d
 {"@timestamp":"2018-01-21T01:50:16.249+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"api:api:cjco4ligo005q0111wz7g0h7f\"}","logger_name":"com.prisma.api.server.ApiServer","thread_name":"single-server-akka.actor.default-dispatcher-38","level":"INFO","level_value":20000,"HOSTNAME":"424e6d2ad611"}
 java.lang.IllegalArgumentException: Unsupported scalar value in SlickExtensions: ListMap(id -> Some(cjco2o7ww0012011133mi90wb))

**Comment by johhansantana** [comment] 2018-01-24 20:46
I'm getting something similar but i don't get an error in the playground, it just doesn't update it at all

with upsert
<img width="1280" alt="screen shot 2018-01-24 at 4 42 02 pm" src="https://user-images.githubusercontent.com/9933887/35356179-0aa7ef0c-0126-11e8-8743-23e5370af167.png">

with regular update
<img width="1280" alt="screen shot 2018-01-24 at 4 42 11 pm" src="https://user-images.githubusercontent.com/9933887/35356192-15a7ad66-0126-11e8-9023-844fa64214fe.png">

**Comment by Huvik** [comment] 2018-01-24 20:53
You i have same problem, with not creating, updating, connecting nested stuff in upsert: 
```
mutation {
  upsertService(where:{
    id:"cjctblxia001c0118lt40frbd"
  }
  create:{
    title:"Novy"
    url: {
      create: {
        link: "test"
        type:BLOG
      }
    }
  }
  update:{
    title:"Update"
    autor:{
      connect:{
        id:"cjcivkjd000et0161qox2rp8s"
      }
    }
  }) {
    id
    title
    url {
      link
      type
    }
    autor {
      name
    }
  }
}
```
From prisma logs: 
```
{"@timestamp":"2018-01-24T20:52:37.965+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"api:api:cjctjq5l9002v0118jqlcpq5j\"}","logger_name":"com.prisma.api.server.ApiServer","thread_name":"single-server-akka.actor.default-dispatcher-18","level":"INFO","level_value":20000,"HOSTNAME":"7d9a37077cd6"}
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
item: DataItem(cjctblxia001c0118lt40frbd,Map(subtitle -> None, updatedAt -> Some(2018-01-24 17:05:31.0), published -> Some(false), createdAt -> Some(2018-01-24 17:05:23.0), content -> None, detail -> None, contentRaw -> None, title -> Some(Update), core -> Some(false)),Some(Service))
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
```

Now there is no error like before with `ListMap`

**Comment by johhansantana** [comment] 2018-01-24 20:59
a workaround for this for the moment (at least my case) is to manually search for the node to update, if it finds it, update it, if not, create it.

**Comment by etx** [comment] 2018-01-28 23:02
Same issue here also, nested creates in an upsert mutation are not working and return no error. Is this a bug or just something that is a WIP?

**Comment by sorenbs** [comment] 2018-01-29 02:00
@do4gr has been working on this part of the code base. Maybe he can shed some light :-)

**Comment by RoryKelly** [comment] 2018-01-29 14:19
I have the Same issue but with upserts in update*** functions as well.

![screen shot 2018-01-29 at 14 16 55](https://user-images.githubusercontent.com/1162214/35514808-50182458-04ff-11e8-956c-657c1cec5ca1.png)

![screen shot 2018-01-29 at 14 17 38](https://user-images.githubusercontent.com/1162214/35514839-66ed8fec-04ff-11e8-803e-0394fe537072.png)

**Comment by etx** [comment] 2018-02-05 14:59
Here is a screenshot of my request. Most of the upsert data is in json as it's generated by my js app. As you can see Prisma does not return any kind of error on the upsert. It does not create or update Blocks and returns an empty array. 

![screen shot 2018-02-05 at 9 51 16 am](https://user-images.githubusercontent.com/285968/35810947-45902d9e-0a5b-11e8-86cd-bcf8e77b2f89.png)

**Comment by lueurxax** [comment] 2018-02-11 12:08
For mutation
`mutation{
  deleteManyCells(where: { OR:[
    {id_:"cjcrb4mtqbki20172j730t1se"},
    {id:"cjcrb4mv9c09o0112pavliu83"}
  ]}){
    count
  }
}`

Error
`
java.lang.ClassCastException: scala.collection.immutable.ListMap$Node cannot be cast to scala.collection.Seq
prisma-database_1  | 	at com.prisma.api.database.QueryArguments$.$anonfun$generateFilterConditions$5(QueryArguments.scala:262)
prisma-database_1  | 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
...
`
But 
`mutation {
  deleteManyCells(where: {id_in: ["cjcrb4mtqbki20172j730t1se", "cjcrb4mv9c09o0112pavliu83"]}) {
    count
  }
}`
execute without errors

**Comment by marktani** [comment] 2018-02-11 12:12
Thanks @lueurxax, this looks to be related to the relational filter!

**Comment by do4gr** [comment] 2018-02-12 15:33
I looked into the issues mentioned here. 
@lueurxax , I can reproduce your error. But it is not related to the upsert case, could you please open a separate bug report for your error?

Regarding the upsert, there is a bug where we at the moment do not execute any nested mutations within upsert. A mutation like this works at the moment:

```graphql
mutation x{ 
  upsertUser(
  		where: {id:"x"},
			update: {name:"y"},
  		create: {name:"z"})
 {name}
}
```
But any nested mutations within the create or update branch are ignored. This is true for a top-level upsert and also if the upsert itself is nested. Any errors on upsert that are not specifically an ignored nested mutation would constitute separate bugs.

Unfortunately the missing nested mutations within upsert are not a trivial bug, so I cannot give an ETA for the fix at the moment.

**Comment by do4gr** [comment] 2018-02-12 16:23
@lueurxax Your issue should be fixed with this PR https://github.com/graphcool/prisma/pull/1879 And will probably roll out tomorrow. So there is no need for a separate bug report anymore. Thanks for reporting the bug!

**Comment by delta98** [comment] 2018-03-28 18:13
I'm still able to replicate this issue.

```
const identifier = context.db.mutation.upsertIdentifier({
        where: { hash },
        create: {
            hash,
            phoneNumber: { connect: { id: node.id } },
            verificationCodes: {
                create: [
                    {
                        code: VerificationCode.generateCode(),
                        validUntil: VerificationCode.generateValidUntil(),
                    },
                ],
            },
        },
        update: {
            hash,
            phoneNumber: { connect: { id: node.id } },
            verificationCodes: {
                create: [
                    {
                        code: VerificationCode.generateCode(),
                        validUntil: VerificationCode.generateValidUntil(),
                    },
                ],
            },
        },
    })
```

`prisma/1.5.1 (darwin-x64) node-v9.8.0`

Successfully creates the parent node, but nested mutations aren't applied. Really appreciate it if this issue could be resolved.

**Comment by Huvik** [comment] 2018-03-28 18:14
You can't connect nodes inside upsert yet, you can see it few messages up

**Comment by Siyfion** [comment] 2018-06-20 14:56
Does anyone else not think that if this functionality is there listed in the Prisma API that it should _**actually do**_ what it says it does "on the tin"? Otherwise it should (temporarily) be removed from the generated API, or at the very least documented in the Prisma documentation here: https://www.prisma.io/docs/reference/prisma-api/mutations-ol0yuoz6go#upserting-nodes

**Comment by bitbrained** [comment] 2018-06-29 20:11
Was this issue resolved with [1.10.0](https://github.com/prismagraphql/prisma/releases/tag/1.10.0)? The change log appears to describe a new feature that resolves this issue, but the linked issue seems unrelated.

> Implemented the execution of connect, disconnect and delete when nested in the create or update branches of an upsert mutation #2565

**Comment by marktani** [comment] 2018-07-04 08:35
All nested mutations inside `upsert` are now supported on the latest `1.12-beta` version: https://github.com/prismagraphql/prisma/releases/tag/1.12.0-beta 🙂

**Comment by dmce** [comment] 2018-07-30 07:21
Hi
I am running 1.12.2 and doing a upsert with a nested create doesnt seem to create the nested item. Added this comment here as this is still open.

![image](https://user-images.githubusercontent.com/464292/43382957-62f6c1e0-93d1-11e8-97cc-d64328f076c2.png)

**Comment by marktani** [comment] 2018-08-02 12:14
This is expected to work on `1.12.x`.

Can you provide a reproduction, @dmce? That is, a datamodel + sequence of mutations that showcase the unexpected behaviour.

**Comment by develomark** [comment] 2018-08-02 18:25
I am getting an internal server error with a `connect` inside an `update` inside of an `upsert`. Something like:

**Comment by marktani** [comment] 2018-08-03 13:40
Thanks @develomark - this should have been fixed on [`1.13.5`](https://github.com/prismagraphql/prisma/releases/tag/1.13.5) [just now](https://github.com/prismagraphql/prisma/commit/117841d7984622fa441effea7eefe6a031afeefd).

With this, I'm closing this issue.

**Closed by marktani** 2018-08-03 13:40 UTC
Labels: kind/bug

**Comment by Oroneki** [comment] 2018-08-03 21:30
It's solved! Thanks!

**Comment by develomark** [comment] 2018-08-03 22:24
@marktani fantastic. Thank you for the speedy fix.

**Comment by danielmahon** [comment] 2018-08-06 20:52
@marktani Is there a reason this won't work? On first call `upsert` is called and a new `stats` relation is created and connected, but the nested `passing` relation isn't. This causes a second call of `upsert` to fail because it cannot `update` the missing relation. Thoughts on what im doing wrong?

```javascript
      await ctx.db.mutation.updatePlayer({
        where: { id: playerToUpdate[0].id },
        data: {
          stats: {
            upsert: {
              create: {
                gamesPlayed: stats.gamesPlayed,
                passing: {
                  create: {
                    passAttempts: stats.passing.passAttempts,
                    passCompletions: stats.passing.passCompletions,
                    passPct: stats.passing.passPct,
                  },
                },
              },
              update: {
                gamesPlayed: stats.gamesPlayed,
                passing: {
                  update: {
                    passAttempts: stats.passing.passAttempts,
                    passCompletions: stats.passing.passCompletions,
                    passPct: stats.passing.passPct,
                  },
                },
              },
            },
          },
        },
      });
```
```graphql
type Player {
  id: ID! @unique
  ...
  stats: Stats
}

type Stats {
  id: ID! @unique
  gamesPlayed: Int
  passing: StatsPassing
}

type StatsPassing {
  id: ID! @unique
  passAttempts: Int
  passCompletions: Int
  passPct: Float
}
```

**Comment by marktani** [comment] 2018-08-08 14:34
@danielmahon I don't see a reason for this failing. Would you mind creating a new issue report for this, so I can take a closer look? Please use the bug template: https://github.com/prismagraphql/prisma/issues/new?template=bug_report.md.
