### ISSUE TITLE
Prisma Restart Loop

### ISSUE THREAD

**Issue by psadeghian** [prismagraphql/prisma#2414] opened 2018-05-13 20:55 UTC
`CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                          PORTS                    NAMES`
`968f80fbbd72        prismagraphql/prisma:1.8   "/bin/sh -c /app/sta…"   8 minutes ago       Restarting (1) 38 seconds ago                            local_prisma-database_1`
`0500c2470abb        mysql:5.7                  "docker-entrypoint.s…"   14 minutes ago      Up 14 minutes                   0.0.0.0:3307->3306/tcp   prisma-db
`

As you can see my Prisma database service container is stuck in a restart loop. I am running my docker containers on a Digital Ocean Droplet. The Droplet is running on an Ubuntu OS. 

I used the following command to start my Prisma database service:
`Prisma local start`

Any guidance on this issue would be greatly appreciated. 

**Please post usage questions or broader discussions in the [Forum](https://www.graph.cool/forum/)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/graphcool/prisma/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/graphcool/prisma/issues/new?template=bug.md)

**Comment by ajaymore** [comment] 2018-05-15 22:01
Same is the issue with me. Below are the containers running on my droplet.

CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                          PORTS                                      NAMES
2b4e2a5b3771        prismagraphql/prisma:1.8                 "/bin/sh -c /app/sta…"   2 minutes ago       Restarting (1) 35 seconds ago                                              local_prisma-database_1
0d89711a9ca7        mysql:5.7                                "docker-entrypoint.s…"   4 hours ago         Up 4 hours                      0.0.0.0:3307->3306/tcp                     prisma-db
fdbded80342c        nginx                                    "nginx -g 'daemon of…"   4 days ago          Up 4 days                       80/tcp                                     site-a
5a93a2546b04        httpd                                    "httpd-foreground"       4 days ago          Up 4 days                       80/tcp                                     site-b
d2a5ef829c1b        jrcs/letsencrypt-nginx-proxy-companion   "/bin/bash /app/entr…"   4 days ago          Up 4 days                                                                  nginx-letsencrypt
eef3f5faded3        jwilder/nginx-proxy                      "/app/docker-entrypo…"   4 days ago          Up 4 days                       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx-proxy

I found below log in docker container:
Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: while scanning a simple key
 in 'string', line 5, column 1:
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A ... 
    ^
could not find expected ':'
 in 'string', line 6, column 1:
    KFXUCsRKtU4s29iIyecDHfyfXsyMBgrv ... 


- Please note I have tried using both versions 1.7 and 1.8 for prisma and documentation at https://www.prisma.io/docs/tutorials/deploy-prisma-servers/digital-ocean-(manual)-texoo6aemu

**Comment by psadeghian** [comment] 2018-05-21 17:49
If you use a Prisma version lower than 1.7 the issue disappears. That said, I was able to work around the issue by using Docker Compose to create my Docker Containers. I then use Docker and Docker Container commands to spin up, stop and kill my containers. In other words, I have been able to set up Prisma database service using Prisma 1.8.

**Comment by marktani** [comment] 2018-05-24 15:19
Hey @psadeghian, `prisma local start` is deprecated.

You now need to run `docker-compose up -d` to start the Prisma server in Docker. I assume this is the cause of the issue, and will therefore close it.

@ajaymore, it seems you are encountering a different problem, please create a new issue if you are still experiencing it :slightly_smiling_face:

**Closed by marktani** 2018-05-24 15:19 UTC

**Comment by jseminck** [comment] 2018-06-24 16:43
Are these docs out of date then: https://github.com/prismagraphql/prisma/blob/master/docs/1.0/03-Tutorials/04-Cluster-Deployment/03-Digital-Ocean-(manual).md ?

It says to run `prisma local start`, which I did, but I see this error in `docker logs <container_id>`:

```
Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: while scanning a simple key
 in 'string', line 5, column 1:
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A ...
    ^
could not find expected ':'
 in 'string', line 6, column 1:
    5sJR9wF6KeoV1ML4rw2lOLkP6FLZawPc ...
    ^
```

**Comment by marktani** [comment] 2018-06-25 16:20
Yes, this tutorial is outdated. We'll [update it soon](https://github.com/prismagraphql/prisma/issues/2314).
